version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:5000
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionString: Server=mssql;Database=practic;User=sa;Password=Your_password123;MultipleActiveResultSets=True;TrustServerCertificate=True;
    ports:
      - "5000:5000"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    container_name: mssql